# Generated by Django 4.2 on 2023-05-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exposure_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_name', models.CharField(max_length=100)),
                ('fac_email', models.EmailField(max_length=100)),
                ('fac_dept', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='honorminor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=100)),
                ('start_sem', models.IntegerField()),
                ('type', models.CharField(max_length=4)),
                ('dept', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('dept', models.CharField(max_length=10)),
                ('pref1', models.CharField(max_length=100)),
                ('pref2', models.CharField(max_length=100)),
                ('pref3', models.CharField(max_length=100)),
                ('pref4', models.CharField(max_length=100)),
                ('pref5', models.CharField(max_length=100)),
                ('pref6', models.CharField(max_length=100)),
                ('pref7', models.CharField(max_length=100)),
                ('pref8', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20)),
                ('stud_name', models.CharField(max_length=60)),
                ('dept', models.CharField(max_length=100)),
                ('sem_pass', models.CharField(max_length=100)),
                ('hon_min', models.CharField(max_length=20)),
                ('kt', models.CharField(max_length=500)),
                ('admit_year', models.CharField(max_length=4)),
                ('opt_course', models.CharField(max_length=500)),
                ('gpa', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=4)),
                ('hm', models.CharField(max_length=40)),
                ('sem', models.IntegerField()),
            ],
        ),
    ]
