# Generated by Django 4.2 on 2023-05-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_alter_student_hon_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='roll_no',
            field=models.BigIntegerField(),
        ),
    ]
