# Generated by Django 4.1.5 on 2023-02-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_admit_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='opt_course',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
