# Generated by Django 4.1.5 on 2023-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem_pass',
            field=models.CharField(max_length=100),
        ),
    ]
