# Generated by Django 4.1.4 on 2023-04-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_admit_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_name', models.CharField(max_length=100)),
                ('fac_email', models.EmailField(max_length=20)),
                ('fc_dept', models.CharField(max_length=5)),
            ],
        ),
    ]
