# Generated by Django 4.1.5 on 2023-04-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='preference',
        ),
    ]
