# Generated by Django 4.1.5 on 2023-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preference', '0002_delete_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=15)),
                ('sem', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=30)),
                ('pref1', models.CharField(max_length=10)),
                ('pref2', models.CharField(max_length=10)),
                ('pref3', models.CharField(max_length=10)),
                ('pref4', models.CharField(max_length=10)),
                ('pref5', models.CharField(max_length=10)),
                ('pref6', models.CharField(max_length=10)),
                ('pref7', models.CharField(max_length=10)),
                ('pref8', models.CharField(max_length=10)),
            ],
        ),
    ]
