# Generated by Django 4.1.4 on 2023-05-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0004_alter_preference_pref1_alter_preference_pref2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='pref1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref5',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref6',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref7',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref8',
            field=models.CharField(max_length=10),
        ),
    ]
