# Generated by Django 4.1.5 on 2023-02-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0003_rename_name_subject_sub_name_subject_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=60)),
                ('dept', models.CharField(max_length=10)),
                ('sem_pass', models.IntegerField()),
                ('hon_min', models.CharField(max_length=20)),
                ('kt', models.ManyToManyField(to='subject.subject')),
            ],
        ),
    ]
