# Generated by Django 4.1.5 on 2023-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_sem_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admit_year',
            field=models.CharField(max_length=4),
        ),
    ]
