# Generated by Django 4.1.4 on 2023-04-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_email',
            field=models.EmailField(max_length=100),
        ),
    ]
