# Generated by Django 4.1.4 on 2023-05-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
