# Generated by Django 4.1.4 on 2023-05-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(max_length=20),
        ),
    ]
