# Generated by Django 4.1.5 on 2023-02-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=8)),
                ('pref_no', models.IntegerField()),
                ('course', models.CharField(max_length=400)),
            ],
        ),
    ]
