# Generated by Django 4.1.5 on 2023-02-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_subject_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='type',
        ),
    ]
