# Generated by Django 4.1.5 on 2023-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_alter_subject_sub_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.AddField(
            model_name='subject',
            name='hm',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(max_length=3),
        ),
    ]
