# Generated by Django 4.1.5 on 2023-04-14 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0017_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('sem', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='honorminor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=100)),
                ('start_sem', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
