# Generated by Django 4.1.5 on 2023-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_rename_name_subject_sub_name_subject_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='optional',
        ),
        migrations.AddField(
            model_name='subject',
            name='sem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='domain',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(max_length=50),
        ),
    ]
