# Generated by Django 4.1.5 on 2023-04-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_remove_subject_domain_remove_subject_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subject',
        ),
    ]
