# Generated by Django 4.1.5 on 2023-04-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
