# Generated by Django 4.1.4 on 2023-04-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0018_exposure_courses_honorminor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exposure_Courses',
        ),
        migrations.DeleteModel(
            name='honorminor',
        ),
    ]
